export default {
  darkMode: 'class',
  content: ['./*.html', './*.js'],
  theme: {
    fontSize: {
      'xs': ['0.75rem', { lineHeight: '1rem' }],
      'sm': ['0.875rem', { lineHeight: '1.25rem' }],
      'base': ['1rem', { lineHeight: '1.5rem' }],
      'lg': ['1.125rem', { lineHeight: '1.75rem' }],
      'xl': ['1.25rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      '5xl': ['3rem', { lineHeight: '1' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
    extend: {
      colors: {
        'primary': '#000000',
        'primary-container': '#F5F5F5',
        'secondary': '#1A1A1A',
        'secondary-container': '#F5F5F5',
        'secondary-fixed-dim': '#D8D8D8',
        'tertiary': '#333333',
        'tertiary-container': '#EBEBEB',
        'tertiary-fixed-dim': '#666666',
        'background': '#F5F5F5',
        'surface': '#FAFAFA',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#FFFFFF',
        'surface-container': '#F0F0F0',
        'surface-container-high': '#E0E0E0',
        'surface-container-highest': '#CCCCCC',
        'surface-variant': '#F8F8F8',
        'surface-dim': '#EEEEEE',
        'on-surface': '#000000',
        'on-surface-variant': '#666666',
        'on-primary': '#FFFFFF',
        'on-secondary': '#FFFFFF',
        'on-tertiary': '#FFFFFF',
        'outline': '#D0D0D0',
        'outline-variant': '#E8E8E8',
        'error': '#1A1A1A',
        'error-container': '#F5F5F5',
      },
      fontFamily: {
        'headline': ['Poppins', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif']
      },
      borderRadius: { 'DEFAULT': '1rem', 'lg': '2rem', 'xl': '3rem', 'full': '9999px' },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
